// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOE5F9-n_mYFM2AUpNviiL-fo3vp01Daw',
    appId: '1:690540812071:web:53476daf8f5995ed21bb02',
    messagingSenderId: '690540812071',
    projectId: 'finalteste-f774e',
    authDomain: 'finalteste-f774e.firebaseapp.com',
    storageBucket: 'finalteste-f774e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5G63GPkfRea5h9xPu57hBKakvZ2BvHYw',
    appId: '1:690540812071:android:89d048e5465f30e221bb02',
    messagingSenderId: '690540812071',
    projectId: 'finalteste-f774e',
    storageBucket: 'finalteste-f774e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxelaPzvggmLwf8VXWTjqSbkC7aRpoAxc',
    appId: '1:690540812071:ios:7a191b63dee02d8921bb02',
    messagingSenderId: '690540812071',
    projectId: 'finalteste-f774e',
    storageBucket: 'finalteste-f774e.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxelaPzvggmLwf8VXWTjqSbkC7aRpoAxc',
    appId: '1:690540812071:ios:7a191b63dee02d8921bb02',
    messagingSenderId: '690540812071',
    projectId: 'finalteste-f774e',
    storageBucket: 'finalteste-f774e.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOE5F9-n_mYFM2AUpNviiL-fo3vp01Daw',
    appId: '1:690540812071:web:8d2efd48c2b458a021bb02',
    messagingSenderId: '690540812071',
    projectId: 'finalteste-f774e',
    authDomain: 'finalteste-f774e.firebaseapp.com',
    storageBucket: 'finalteste-f774e.appspot.com',
  );
}
